### ISSUE TITLE
node creation race condition?

### ISSUE THREAD

**Issue by dsmiley** [kontena/kontena-plugin-aws#8]
I used "kontena aws node create" with a ton of options plus my desired machine name "node2" at the end... and I got this error:
```
/brew/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.5/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The instance ID 'i-01cff287c8d59f6f5' does not exist (Exception)
	from /brew/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.5/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /brew/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.5/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
	from /brew/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.5/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /brew/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.5/lib/seahorse/client/request.rb:70:in `send_request'
	from /brew/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.5/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /brew/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.5.5/lib/aws-sdk-resources/request.rb:24:in `call'
	from /brew/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.5.5/lib/aws-sdk-resources/operations.rb:41:in `call'
	from /brew/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.5.5/lib/aws-sdk-resources/operations.rb:61:in `call'
	from /brew/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.5.5/lib/aws-sdk-resources/resource.rb:147:in `load'
	from /brew/lib/ruby/gems/2.3.0/gems/kontena-plugin-aws-0.1.0/lib/kontena/machine/aws/node_provisioner.rb:87:in `block in run!'
	from /brew/lib/ruby/gems/2.3.0/gems/shell-spinner-1.0.4/lib/shell-spinner.rb:48:in `block in with_spinner'
```

Yet I ultimately found that the node was created and added to the group.  This stack trace/error happened for me just once; the other few times I've done it, things were fine.

**Comment by dsmiley** [comment]
BTW the node that was successfully created here despite this exception has no labels.

**Comment by jnummelin** [comment]
hmm, looking at the code the provisioner has managed to even create the tags for the instance, why on earth would the state reload call give "not exist". Well, it would not be the first peculiarity with AWS APIs... :)

Anyways, it might be better to switch to use the AWS SDK "waiters" instead of "manually" polling for the state:
https://github.com/aws/aws-sdk-ruby#waiters

**Comment by dsmiley** [comment]
A general question -- is there much "value-add" in the Kontena AWS module over using AWS's CLI with CoreOS AMI?  If I try to do the latter, what will I be missing out on?  I like that AWS can read my access & secret keys from a config file, and of course it has loads of options.

**Comment by jnummelin** [comment]
I don't think you will miss anything, everything and more can be achieved with directly using AWS CLI or other tools such as Terraform, Cloudformation, ...

From our point of view this plugin creates rather easily pretty decent default configuration that works for most people. Especially handy for "kicking tires". :)

**Comment by jakolehm** [comment]
Error has been fixed: https://github.com/kontena/kontena/pull/1000
